### PR TITLE
use command "magick" because "convert" doesn't seem to work

### PR DESCRIPTION
**Pull request by M3psipax**
Please consider this small change to your project.

After installing the newest version of the system dependencies, I found the "convert" command to not be working on its own with ImageMagick Q8 v7.0.10-3.

Using "magick convert" or simply "magick" fixed my issue.

Thanks for your work.

### CODE REVIEW

**Comment by dpoetzsch** [comment]
I believe this is a windows-only issue and should therefore only be fixed for windows :)

**Comment by marcdacz** [comment]
I'll check this out on both my PC and mac.
Will find out what we can do to dynamically change command per OS.

**Comment by marcdacz** [comment]
Oh I see that you've handled it already.
I'll run some tests and will merge it then.
Great job and thanks for using this module.

**Comment by M3psipax** [comment]
Cool. Thank you!

**Pull request merged**
